### ISSUE TITLE
NG 103 (ACK 未受信)となる

### ISSUE THREAD

**Issue by hagisuke** [AmbientDataInc/LoRa-rssi-measure#1]
個人でEASELのES920LRを２つ購入し、通信実験をするため「Raspberry Pi3とArduinoのLoRa通信」の記事を参考にしていたのですが、公開していただいているコードをそのまま利用すると、
発信側のプログラムESP_GPS_LoRa.inoの関数send2LoRa()の中の157行目で、「NG 103 (ACK 未受信)」が返ってきてしまいました。
ack やpanidなどについて対向通信のための設定を何かされていますでしょうか？
素人質問で恐縮ですが、ご教授いただければ幸いです。

http://easel5.com/download/es920lr/ES920LRコマンド仕様ソフトウェア説明書.pdf

**Comment by TakehikoShimojima** [comment]
特に設定はしていなかったと思います。Raspberry Pi側は先に起動してあるのですよね？

Raspberry Pi + ES920LRとArduino + ES920LRの組み合わせで通信する前に、
EASEL社の評価ボード + ES920RLの対向で通信を確認し、それが確認できたら
一方をArduino + ES920LRに変えて動かしてみるといったように、ステップ・バイ
・ステップで動作確認しながら進めるのが結果的に早いように思います。

**Comment by hagisuke** [comment]
ご回答ありがとうございます。
その後コマンド仕様ソフトウェア説明書を確認しながら試したのですが、
親機側のプログラムのsetMode関数に、以下の４行を追加したところ通信に成功いたしました。
sendcmd('node 1\r\n') //親機に設定
sendcmd('ownid 0000\r\n') //自ノードアドレスを0に
sendcmd('rssi 1\r\n')
sendcmd('rcvid 1\r\n')
評価ボードでの確認を経ずに通信実験をしたため、親機のアドレス設定ができていなかったようです。
無事解決いたしました。素早いご返信ありがとうございました。
